multi_auth/routes/web.php
<?php

use App\Http\Controllers\Admin\BusRegController;
use App\Http\Controllers\Admin\CoachfacilityController;
use App\Http\Controllers\Admin\CoachTypeController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\TripRouteController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\TicketPriceController;
use App\Http\Controllers\Admin\TripAssignController;
use App\Http\Controllers\Admin\TripManageContoller;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('admin/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'is_admin'])->group(function () {

    Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.route');

    // Manage Company 
    Route::get('admin/company-list', [CompanyController::class, 'index'])->name('admin.company.list');
    Route::get('admin/add-company', [CompanyController::class, 'create'])->name('admin.add.company');
    Route::post('admin/save-company', [CompanyController::class, 'save'])->name('admin.save.company');
    Route::get('admin/edit-company/{id}', [CompanyController::class, 'edit'])->name('admin.edit.company');
    Route::post('admin/update-company', [CompanyController::class, 'update'])->name('admin.update.company');
    Route::get('admin/delete-company/{id}', [CompanyController::class, 'delete'])->name('admin.delete.company');

    // Manage User
    Route::get('admin/admin-list', [UserController::class, 'index'])->name('admin.list');
    Route::get('admin/create-admin', [UserController::class, 'create'])->name('admin.add');
    Route::post('admin/save-admin', [UserController::class, 'save'])->name('admin.save');

    // Manage Coach type 
    Route::get('admin/coach-type-list', [CoachTypeController::class, 'index'])->name('admin.coach.type.list');
    Route::get('admin/add-coach-type', [CoachTypeController::class, 'create'])->name('admin.add.coach.type');
    Route::post('admin/save-coach-type', [CoachTypeController::class, 'save'])->name('admin.save.coach.type');

    // Manage coach facelity 
    Route::get('admin/coach-facility-list', [CoachfacilityController::class, 'index'])->name('admin.coach.facelity.list');
    Route::get('admin/add-coach-facility', [CoachfacilityController::class, 'create'])->name('admin.add.coach.facelity');
    Route::post('admin/save-coach-facility', [CoachfacilityController::class, 'save'])->name('admin.save.coach.facility');

    // Manage Bus registration
    Route::get('admin/bus-list', [BusRegController::class, 'index'])->name('admin.bus.list');
    Route::get('admin/bus-reg', [BusRegController::class, 'create'])->name('admin.bus.reg');
    Route::post('admin/bus-add', [BusRegController::class, 'save'])->name('admin.bus.add');
    Route::get('admin/bus-edit/{id}', [BusRegController::class, 'edit'])->name('admin.bus.edit');
    Route::post('admin/get-company-facility', [BusRegController::class, 'getCoachtypeAndfacility'])->name('admin.get.company.facility');
    Route::post('admin/bus-update', [BusRegController::class, 'update'])->name('admin.bus.update');
    Route::get('admin/bus-delete/{id}', [BusRegController::class, 'delete'])->name('admin.bus.delete');

    // Manage Drivers
    Route::get('admin/driver-list', [DriverController::class, 'index'])->name('admin.driver.list');
    Route::get('admin/driver-create', [DriverController::class, 'create'])->name('admin.driver.create');
    Route::post('admin/driver-save', [DriverController::class, 'save'])->name('admin.driver.save');
    Route::get('admin/driver-edit/{id}', [DriverController::class, 'edit'])->name('admin.driver.edit');
    Route::post('admin/driver-update', [DriverController::class, 'update'])->name('admin.driver.update');
    Route::get('admin/driver-delete/{id}', [DriverController::class, 'delete'])->name('admin.driver.delete');

    // Location list
    Route::get('admin/location-list', [LocationController::class, 'index'])->name('admin.location.list');
    Route::get('admin/location-create', [LocationController::class, 'create'])->name('admin.location.create');
    Route::post('admin/location-save', [LocationController::class, 'save'])->name('admin.location.save');
    Route::get('admin/location-edit/{id}', [LocationController::class, 'edit'])->name('admin.location.edit');
    Route::post('admin/location-update', [LocationController::class, 'update'])->name('admin.location.update');
    Route::get('admin/location-delete/{id}', [LocationController::class, 'delete'])->name('admin.location.delete');

    // Trip route manage
    Route::get('admin/route-list', [TripRouteController::class, 'index'])->name('admin.route.list');
    Route::get('admin/route-create', [TripRouteController::class, 'create'])->name('admin.route.create');
    Route::post('admin/route-save', [TripRouteController::class, 'save'])->name('admin.route.save');
    Route::get('admin/route-edit/{id}', [TripRouteController::class, 'edit'])->name('admin.route.edit');
    Route::post('admin/route-update', [TripRouteController::class, 'index'])->name('admin.route.update');
    Route::get('admin/route-delete/{id}', [TripRouteController::class, 'soft_delete'])->name('admin.route.delete');
    Route::post('admin/getCompanyRouteInfo', [TripRouteController::class, 'getCompanyRouteInfo'])->name('admin.get.company.route.info');

    // Counter manage
    Route::resource('admin/counter', CounterController::class);
    // Trip assign manage
    Route::resource('admin/trip-assign', TripAssignController::class);
    Route::post('admin/bus-info', [BusRegController::class, 'companyBusInfo'])->name('admin.companyBusInfo');
    Route::get('admin/trip-assing-edit/{id}', [TripAssignController::class, 'edit'])->name('trip.assign.edit');
    Route::post('amin/trip-assing-update', [TripAssignController:: class, 'update'])->name('trip-assign.update');
    Route::post('admin/getCompanyRoute', [TripRouteController::class, 'getCompanyRoute'])->name('admin.getCompanyRoute');

    // Ticket price 
    Route::resource('admin/ticket-price', TicketPriceController::class);
    Route::get('admin/ticket-price-edit/{id}', [TicketPriceController::class, 'edit'])->name('ticket.price.edit');
    Route::post('admin/ticket-price-update', [TicketPriceController::class, 'update'])->name('ticket-price.update');
    Route::post('getCompanyRouteCoach', [TicketPriceController::class, 'getCompanyRouteCoach'])->name('getCompanyRouteCoach');
    Route::post('getStoppage', [TripRouteController::class, 'getStoppage'])->name('getStoppage');
    Route::post('getticketprice', [TicketPriceController::class, 'getticketprice'])->name('get.ticket.price');

    // Trip search manage
    Route::get('admin/trip-search', [TripManageContoller::class, 'index'])->name('trip.search.index');
    Route::post('admin/trip-search', [TripManageContoller::class, 'gettriplist'])->name('gettriplist');
    Route::get('admin/seat-view/{id}', [TripManageContoller::class, 'seat_view'])->name('admin.seat.view');


});

multi_auth/app/Models/TicketPrice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TicketPrice extends Model
{
    use HasFactory;
    
    public function getIdAttribute( $value )
    {
        return encryptIt( $value );
    }

    public static function getAll()
    {
        return self::select('ticket_prices.id', 'companies.companyName', 'trip_routes.routeName', 'coach_types.title', 'ticket_prices.endPointOf', 'ticket_prices.price', 'ticket_prices.soft_delete')
                    ->join('companies', 'companies.id', '=', 'ticket_prices.company_id')
                    ->join('trip_routes', 'trip_routes.id', '=', 'ticket_prices.trip_route_id')
                    ->join('coach_types', 'coach_types.id', '=', 'ticket_prices.coach_type_id')
                    ->get();
    }
}

multi_auth/app/Http/Controllers/Admin/TicketPriceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\TicketPrice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\CoachType;
use App\Models\Company;
use App\Models\TripRoute;
use Illuminate\Support\Facades\Auth;

class TicketPriceController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $ticketPrices = TicketPrice::getAll();
        return view('admin.ticketprice.list', compact('ticketPrices'));
    }

    public function getCompanyRouteCoach(Request $request)
    {
        $company_id = $request->input('company_id');
        $data['routeName'] = TripRoute::select('id', 'routeName')->where([['company_id', '=', $company_id],['status', '=', 1], ['soft_delete', '=', 0]])->get();
        $data['coachTypes'] = CoachType::select('id', 'title')->where('company_id', '=', $company_id)->where('status', '=', 1)->get();
        return response()->json($data);
    }

    public function create()
    {
        $id = Auth::user()->company_id;
        $companies = Company::select('id', 'companyName')->get();

        if (is_super_admin()) {
            $companies = Company::select('id', 'companyName')->get();
            $routeName = [];
            $coachTypes = [];
        } else {
            $company_id = [];
            $routeName = TripRoute::select('id', 'routeName', 'stoppage')->where('company_id', '=', $id)->where('status', '=', 1)->where('soft_delete', '=', 0)->get();
            
            $coachTypes = CoachType::select('id', 'title')->where('company_id', '=', $id)->where('status', '=', 1)->get();
        }
        
        return view('admin.ticketprice.create', compact('companies', 'routeName', 'coachTypes'));
    }

    public function store(Request $request, TicketPrice $ticketPrice)
    {
        $request->validate([
            'trip_route'    => 'required',
            'coach_type'    => 'required',
            'price'         => 'required'
        ]);

        $ticketPrice->company_id    = is_super_admin() ? $request->input('company') : Auth::user()->company_id;
        $ticketPrice->trip_route_id = decryptIt($request->input('trip_route'));
        $ticketPrice->coach_type_id = $request->input('coach_type');
        $ticketPrice->endPointOf      = $request->input('endPointOf');
        $ticketPrice->price         = $request->input('price');
        $result = $ticketPrice->save();

        if ($result) {
            return redirect()->route('ticket-price.index')->with('success', 'Ticket Price Added Successfully!');
        } else {
            return back()->with('warning', 'Something Wrong, Please Try again');
        }
    }


    public function show(TicketPrice $ticketPrice)
    {
        //
    }

    public function edit($id, TicketPrice $ticketPrice)
    {
        $tp_Id = decryptIt($id);
        
        $ticketPriceId = $ticketPrice->find($tp_Id)->first();
        $id =  $ticketPriceId->company_id;
        
        $routeName = TripRoute::select('id', 'routeName')->where('company_id', '=', $id)->where('status', '=', 1)->where('soft_delete', '=', 0)->get();
        $coachTypes = CoachType::select('id', 'title')->where('company_id', '=', $id)->where('status', '=', 1)->get();
        
        return view('admin.ticketprice.edit', compact('routeName', 'coachTypes', 'ticketPriceId' ));
    }

    public function update(Request $request, TicketPrice $ticketPrice)
    {
        $request->validate([
            'trip_route'    => 'required',
            'coach_type'    => 'required',
            'stoppage'      => 'required',
            'price'         => 'required'
        ]);
        $id = decryptIt($request->id);
        $getResult = $ticketPrice->find($id);

        $getResult->trip_route_id = decryptIt($request->trip_route);
        $getResult->coach_type_id = $request->coach_type;
        $getResult->stoppage      = $request->stoppage;
        $getResult->price         = $request->price;
        $result = $getResult->save();

        if ($result) {
            return redirect()->route('ticket-price.index')->with('success', 'Ticket Price Update Successfully!');
        } else {
            return back()->with('warning', 'Something Wrong, Please Try again');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TicketPrice  $ticketPrice
     * @return \Illuminate\Http\Response
     */
    public function destroy(TicketPrice $ticketPrice)
    {
        //
    }

    public function getticketprice(Request $request, TicketPrice $ticketPrice)
    {
        $dropingPoint =  $request->input('dropingPoint');
        $company_id =  $request->input('company_id');
        $trip_route_id =  $request->input('trip_route_id');

        $getprice = TicketPrice::select('price')
                        ->where([
                            ['company_id', '=', $company_id],
                            ['trip_route_id', '=', $trip_route_id],
                            ['endPointOf', '=', $dropingPoint]
                        ])->first();
        return response()->json($getprice);
    }
}

multi_auth/resources/views/admin/ticketprice/create.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- stype here -->

@endsection()

@section('main_content')

<h1 class="h3 mb-4 text-gray-800">{{ __('Add Ticket Price') }}
    <a class="btn btn-primary float-right" href="{{ route('ticket-price.index') }}">Back</a>
</h1>

<div class="card">
    <div class="card-body">
        @if( $msg = Session::get('warning') )
        <div class="alert alert-danger" role="alert">
            {{ $msg }}
        </div>
        @endif

        <form method="POST" action="{{ route('ticket-price.store') }}">
            @csrf
            <div class="form-row">
                @if( is_super_admin() )
                <div class="form-group col-md-6">
                    <label for="company">Company</label>
                    <select name="company" id="company" class="form-control" onChange="getCompanylocation(this.value)">
                        <option value="">Select one</option>
                        @foreach( $companies as $company)
                        <option value="{{ $company->id }}">{{ $company->companyName }}</option>
                        @endforeach
                    </select>
                    <small id='alert_company' class="form-text text-danger"></small>
                    @error('company')
                    <small id="company" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                @endif

                <div class="form-group col-md-6">
                    <label for="trip_route">Route Name</label>
                    <select class="form-control" name="trip_route" id="trip_route" onchange="getStoppage(this.value)">
                        <option value="">Select One</option>
                        @foreach( $routeName as $name)
                        <option value="{{$name->id}}">{{ $name->routeName}}</option>
                        @endforeach
                    </select>
                    <small id='routemsg' class="form-text text-danger"></small>
                    @error('trip_route')
                    <small id="trip_route" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="coach_type">Coach Type</label>
                    <select class="form-control" name="coach_type" id="coach_type">
                        <option value="">Select One</option>
                        @foreach( $coachTypes as $coachType)
                        <option value="{{ $coachType->id }}">{{ $coachType->title }}</option>
                        @endforeach
                    </select>
                    <small id='coachtypemsg' class="form-text text-danger"></small>
                    @error('coach_type')
                    <small id="coach_type" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="stoppage">Droping Point</label>
                    <select class="form-control" name="endPointOf" id="endPointOf">
                        <!-- <option value="">Select One</option> -->
                        
                    </select>
                    <small id='stoppageErrmsg' class="form-text text-danger"></small>
                    @error('stoppage')
                    <small id="stoppage" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="price">Ticket Pirce</label>
                    <div class="input-group">
                        <input type="number" id="price" class="form-control" name="price">
                        <div class="input-group-append">
                            <span class="input-group-text" id="basic-addon2">BDT</span>
                        </div>
                    </div>
                    @error('price')
                    <small id="price" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>


@endsection()


@section('custom_js')
<!-- seript here -->
<script>

    function getCompanylocation(id) {
        let company_id = id,
            company_select, routemsg, coachtypemsg;

        company_select = document.getElementById('alert_company');
        routemsg = document.getElementById('routemsg');
        coachtypemsg = document.getElementById('coachtypemsg');

        company_select.textContent = '';
        routemsg.innerHTML = '';
        coachtypemsg.innerHTML = '';

        let route_name = `<option value=''>Select One</option>`;
        let coach_type = `<option value=''>Select One</option>`;

        if (company_id !== '') {
            $.ajax({
                url: "{{ route('getCompanyRouteCoach')}}",
                type: 'POST',
                dataType: 'json',
                data: {
                    _token: '{{ csrf_token() }}',
                    company_id: company_id
                },
                success: function(r) {
                    coachTypes = r.coachTypes;
                    routeName = r.routeName;

                    if (coachTypes.length !== 0) {
                        for (const i in coachTypes) {
                            coach_type += `<option value='${coachTypes[i].id}'>${coachTypes[i].title}</option>`;
                        }
                    } else {
                        coachtypemsg.innerHTML = `Please insert coach route first <a href="{{route('admin.add.coach.type')}}">Go</a>`;
                    }

                    if (routeName.length !== 0) {
                        for (const i in routeName) {
                            route_name += `<option value='${routeName[i].id}'>${routeName[i].routeName}</option>`;
                        }
                    } else {
                        routemsg.innerHTML = `Please insert coach type first <a href="{{route('admin.route.create')}}">Go</a>`;
                    }
                    document.getElementById("coach_type").innerHTML = coach_type;
                    document.getElementById("trip_route").innerHTML = route_name;
                }
            });

        } else {
            company_select.textContent = 'Select Company';
            document.getElementById("coach_type").innerHTML = coach_type;
            document.getElementById("trip_route").innerHTML = route_name;
        }
    }

    function getStoppage(id){
        let route_id = id, endPointOf, routemsg, stoppage, stoppageErrmsg;

        routemsg        = document.getElementById('routemsg');
        endPointOf    = document.getElementById('endPointOf');
        stoppageErrmsg  = document.getElementById('stoppageErrmsg');

        routemsg.textContent    = '';
        endPointOf.innerHTML  = `<option value=''>Select One</option>`;

        if ( route_id !== '' ) {
            $.ajax({
                url: "{{ route('getStoppage')}}",
                type: 'POST',
                dataType: 'json',
                data: {
                    _token: '{{ csrf_token() }}',
                    route_id: route_id
                },
                success: function(r) {
                    let endPoint = r.endPointOf;
                    if(endPoint.length !== 0 ){
                        for ( const i in endPoint) {
                            stoppage += `<option value='${endPoint[i].locationName}'>${endPoint[i].locationName}</option>`;
                        }
                    } else {
                        stoppageErrmsg.innerHTML = `Please <a href="{{ route('admin.location.create')}}">Go</a> for insert location`;
                    }
                    endPointOf.innerHTML = stoppage;
                }
            });
        } else {
            routemsg.textContent = 'Please select Route name';
        }
    }
</script>

@endsection()

multi_auth/resources/views/admin/ticketprice/edit.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- stype here -->

@endsection()

@section('main_content')

<h1 class="h3 mb-4 text-gray-800">{{ __('Ticket Price Update') }}
    <a class="btn btn-primary float-right" href="{{ route('ticket-price.index') }}">Back</a>
</h1>

<div class="card">
    <div class="card-body">
        @if( $msg = Session::get('warning') )
        <div class="alert alert-danger" role="alert">
            {{ $msg }}
        </div>
        @endif

        <form method="POST" action="{{ route('ticket-price.update') }}">
            @csrf
            <input type="hidden" name="id" value="{{ $ticketPriceId->id }}">
            <div class="form-row">

                <div class="form-group col-md-6">
                    <label for="trip_route">Route Name</label>
                    <select class="form-control" name="trip_route" id="trip_route">
                        <option value="">Select One</option>
                        @foreach( $routeName as $name)
                        <?php $name->id === encryptIt($ticketPriceId->trip_route_id) ? $selected = 'selected' : $selected = ''?>
                        <option {{ $selected }} value="{{$name->id}}">{{ $name->routeName}}</option>
                        @endforeach
                    </select>
                    <small id='routemsg' class="form-text text-danger"></small>
                    @error('trip_route')
                    <small id="trip_route" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="coach_type">Coach Type</label>
                    <select class="form-control" name="coach_type" id="coach_type">
                        <option value="">Select One</option>
                        @foreach( $coachTypes as $coachType)
                        
                        <?php $coachType->id === $ticketPriceId->coach_type_id ? $selected = 'selected' : $selected = ''?>
                        <option {{ $selected }} value="{{ $coachType->id }}">{{ $coachType->title }}</option>
                        @endforeach
                    </select>
                    <small id='coachtypemsg' class="form-text text-danger"></small>
                    @error('coach_type')
                    <small id="coach_type" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="price">Ticket Pirce</label>
                    <div class="input-group">
                        <input type="number" id="price" class="form-control" name="price" value="{{ $ticketPriceId->price}}">
                        <div class="input-group-append">
                            <span class="input-group-text" id="basic-addon2">BDT</span>
                        </div>
                    </div>
                    @error('price')
                    <small id="price" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>


@endsection()


@section('custom_js')
<!-- seript here -->
<script>
    $(function() {
        $("#stoppage").select2();
    });

    function getCompanylocation(id) {
        let company_id = id,
            company_select, routemsg, coachtypemsg;

        company_select = document.getElementById('alert_company');
        routemsg = document.getElementById('routemsg');
        coachtypemsg = document.getElementById('coachtypemsg');

        company_select.textContent = '';
        routemsg.textContent = '';
        coachtypemsg.textContent = '';

        let route_name = `<option value=''>Select One</option>`;
        let coach_type = `<option value=''>Select One</option>`;

        if (company_id !== '') {
            $.ajax({
                url: "{{ route('getCompanyRouteCoach')}}",
                type: 'POST',
                dataType: 'json',
                data: {
                    _token: '{{ csrf_token() }}',
                    company_id: company_id
                },
                success: function(r) {
                    coachTypes = r.coachTypes;
                    routeName = r.routeName;

                    if (coachTypes.length !== 0) {
                        for (const i in coachTypes) {
                            coach_type += `<option value='${coachTypes[i].id}'>${coachTypes[i].title}</option>`;
                        }
                    } else {
                        coachtypemsg.innerHTML = `Please insert coach route first <a href="{{route('admin.add.coach.type')}}">Go</a>`;
                    }

                    if (routeName.length !== 0) {
                        for (const i in routeName) {
                            route_name += `<option value='${routeName[i].id}'>${routeName[i].routeName}</option>`;
                        }
                    } else {
                        routemsg.innerHTML = `Please insert coach route first <a href="{{route('admin.route.create')}}">Go</a>`;
                    }
                    document.getElementById("coach_type").innerHTML = coach_type;
                    document.getElementById("trip_route").innerHTML = route_name;

                }
            });

        } else {
            company_select.innerHTML = 'Select Company';
            document.getElementById("coach_type").innerHTML = coach_type;
            document.getElementById("trip_route").innerHTML = route_name;
        }


    }
</script>

@endsection()

multi_auth/resources/views/admin/ticketprice/list.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- style here -->

@endsection

@section('main_content')
<h1 class="h3 mb-4 text-gray-800">{{ __('Ticket Price list') }}
    <a class="btn btn-primary float-right" href="{{ route('ticket-price.create')}}">Add New</a>
</h1>
@if( $msg = Session::get('success') )
<div class="alert alert-primary" role="alert">
    {{ $msg }}
</div>
@endif
<div class="card">

    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-hover table-sm">
            <thead>
                <tr>
                    <th scope="col">Sl</th>
                    @if( is_super_admin() )
                    <th scope="col">Company Name</th>
                    @endif
                    <th scope="col">Route Name</th>
                    <th scope="col">Coach Type</th>
                    <th scope="col">End point</th>
                    <th scope="col">Ticket Pirce</th>
                    @if( is_super_admin() )
                    <th scope="col">Is Deleted</th>
                    @endif
                    
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 0; ?>
                @foreach( $ticketPrices as $tp )
                <?php $i++; ?>
                <tr>
                    <td>{{ $i }}</td>
                    @if( is_super_admin() )
                    <td>{{ $tp->companyName }}</td>
                    @endif
                    <td>{{ $tp->routeName }}</td>
                    <td>{{ $tp->title }}</td>
                    <td>{{ $tp->endPointOf }}</td>
                    <td>{{ $tp->price }}</td>
                    @if( is_super_admin() )
                    <td>{{ is_deleted($tp->soft_delete) }}</td>
                    @endif
                    
                    <td>
                    <!-- <form action="Post"></form> -->

                        <a class="text-primary" href="{{ route('ticket.price.edit', ['id' => $tp->id]) }}"><i class="fa fa-edit "></i></a>
                        ||
                        <a class="text-danger"  id="delete-route" data-toggle="modal" data-target="#deleteroute" url="{{ route('admin.route.delete',['id' => $tp->id])}}"><i class="fa fa-trash "></i></a>

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>



<!-- temporary delete bus -->
<div class="modal fade" id="deleteroute" tabindex="-1" role="dialog" aria-labelledby="deleteroute" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Delete Bus Information?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Delete carefully, You are not retrieve Bus Information.</div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary text-white" id="route-delete-btn">Delete</a>
            </div>
        </div>
    </div>
</div>
@endsection

@section('custom_js')
<!-- seript here -->

<script>

    $(function() {
        $('#delete-route').click(function() {
            let id = $(this).attr('url');
            $('#route-delete-btn').attr({
                href: id
            });
        });
    });
</script>

@endsection