multi_auth/routes/web.php
<?php

use App\Http\Controllers\Admin\BusRegController;
use App\Http\Controllers\Admin\CoachfacilityController;
use App\Http\Controllers\Admin\CoachTypeController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\TripRouteController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\TicketPriceController;
use App\Http\Controllers\Admin\TripAssignController;
use App\Http\Controllers\Admin\TripManageContoller;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('admin/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'is_admin'])->group(function () {

    Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.route');

    // Manage Company 
    Route::get('admin/company-list', [CompanyController::class, 'index'])->name('admin.company.list');
    Route::get('admin/add-company', [CompanyController::class, 'create'])->name('admin.add.company');
    Route::post('admin/save-company', [CompanyController::class, 'save'])->name('admin.save.company');
    Route::get('admin/edit-company/{id}', [CompanyController::class, 'edit'])->name('admin.edit.company');
    Route::post('admin/update-company', [CompanyController::class, 'update'])->name('admin.update.company');
    Route::get('admin/delete-company/{id}', [CompanyController::class, 'delete'])->name('admin.delete.company');

    // Manage User
    Route::get('admin/admin-list', [UserController::class, 'index'])->name('admin.list');
    Route::get('admin/create-admin', [UserController::class, 'create'])->name('admin.add');
    Route::post('admin/save-admin', [UserController::class, 'save'])->name('admin.save');

    // Manage Coach type 
    Route::get('admin/coach-type-list', [CoachTypeController::class, 'index'])->name('admin.coach.type.list');
    Route::get('admin/add-coach-type', [CoachTypeController::class, 'create'])->name('admin.add.coach.type');
    Route::post('admin/save-coach-type', [CoachTypeController::class, 'save'])->name('admin.save.coach.type');

    // Manage coach facelity 
    Route::get('admin/coach-facility-list', [CoachfacilityController::class, 'index'])->name('admin.coach.facelity.list');
    Route::get('admin/add-coach-facility', [CoachfacilityController::class, 'create'])->name('admin.add.coach.facelity');
    Route::post('admin/save-coach-facility', [CoachfacilityController::class, 'save'])->name('admin.save.coach.facility');

    // Manage Bus registration
    Route::get('admin/bus-list', [BusRegController::class, 'index'])->name('admin.bus.list');
    Route::get('admin/bus-reg', [BusRegController::class, 'create'])->name('admin.bus.reg');
    Route::post('admin/bus-add', [BusRegController::class, 'save'])->name('admin.bus.add');
    Route::get('admin/bus-edit/{id}', [BusRegController::class, 'edit'])->name('admin.bus.edit');
    Route::post('admin/get-company-facility', [BusRegController::class, 'getCoachtypeAndfacility'])->name('admin.get.company.facility');
    Route::post('admin/bus-update', [BusRegController::class, 'update'])->name('admin.bus.update');
    Route::get('admin/bus-delete/{id}', [BusRegController::class, 'delete'])->name('admin.bus.delete');

    // Manage Drivers
    Route::get('admin/driver-list', [DriverController::class, 'index'])->name('admin.driver.list');
    Route::get('admin/driver-create', [DriverController::class, 'create'])->name('admin.driver.create');
    Route::post('admin/driver-save', [DriverController::class, 'save'])->name('admin.driver.save');
    Route::get('admin/driver-edit/{id}', [DriverController::class, 'edit'])->name('admin.driver.edit');
    Route::post('admin/driver-update', [DriverController::class, 'update'])->name('admin.driver.update');
    Route::get('admin/driver-delete/{id}', [DriverController::class, 'delete'])->name('admin.driver.delete');

    // Location list
    Route::get('admin/location-list', [LocationController::class, 'index'])->name('admin.location.list');
    Route::get('admin/location-create', [LocationController::class, 'create'])->name('admin.location.create');
    Route::post('admin/location-save', [LocationController::class, 'save'])->name('admin.location.save');
    Route::get('admin/location-edit/{id}', [LocationController::class, 'edit'])->name('admin.location.edit');
    Route::post('admin/location-update', [LocationController::class, 'update'])->name('admin.location.update');
    Route::get('admin/location-delete/{id}', [LocationController::class, 'delete'])->name('admin.location.delete');

    // Trip route manage
    Route::get('admin/route-list', [TripRouteController::class, 'index'])->name('admin.route.list');
    Route::get('admin/route-create', [TripRouteController::class, 'create'])->name('admin.route.create');
    Route::post('admin/route-save', [TripRouteController::class, 'save'])->name('admin.route.save');
    Route::get('admin/route-edit/{id}', [TripRouteController::class, 'edit'])->name('admin.route.edit');
    Route::post('admin/route-update', [TripRouteController::class, 'index'])->name('admin.route.update');
    Route::get('admin/route-delete/{id}', [TripRouteController::class, 'soft_delete'])->name('admin.route.delete');
    Route::post('admin/getCompanyRouteInfo', [TripRouteController::class, 'getCompanyRouteInfo'])->name('admin.get.company.route.info');

    // Counter manage
    Route::resource('admin/counter', CounterController::class);
    // Trip assign manage
    Route::resource('admin/trip-assign', TripAssignController::class);
    Route::post('admin/bus-info', [BusRegController::class, 'companyBusInfo'])->name('admin.companyBusInfo');
    Route::get('admin/trip-assing-edit/{id}', [TripAssignController::class, 'edit'])->name('trip.assign.edit');
    Route::post('amin/trip-assing-update', [TripAssignController:: class, 'update'])->name('trip-assign.update');
    Route::post('admin/getCompanyRoute', [TripRouteController::class, 'getCompanyRoute'])->name('admin.getCompanyRoute');

    // Ticket price 
    Route::resource('admin/ticket-price', TicketPriceController::class);
    Route::get('admin/ticket-price-edit/{id}', [TicketPriceController::class, 'edit'])->name('ticket.price.edit');
    Route::post('admin/ticket-price-update', [TicketPriceController::class, 'update'])->name('ticket-price.update');
    Route::post('getCompanyRouteCoach', [TicketPriceController::class, 'getCompanyRouteCoach'])->name('getCompanyRouteCoach');
    Route::post('getStoppage', [TripRouteController::class, 'getStoppage'])->name('getStoppage');
    Route::post('getticketprice', [TicketPriceController::class, 'getticketprice'])->name('get.ticket.price');

    // Trip search manage
    Route::get('admin/trip-search', [TripManageContoller::class, 'index'])->name('trip.search.index');
    Route::post('admin/trip-search', [TripManageContoller::class, 'gettriplist'])->name('gettriplist');
    Route::get('admin/seat-view/{id}', [TripManageContoller::class, 'seat_view'])->name('admin.seat.view');


});

multi_auth/app/Models/Counter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Counter extends Model
{
    use HasFactory;

    function getIdAttribute($value)
    {
        return encryptIt($value);
    }
    public static function getAll()
    {
        return self::select( 'counters.id','counters.counterName', 'companies.companyName', 'locations.locationName', 'counters.address', 'counters.status', 'counters.soft_delete')
                ->join('companies', 'companies.id', '=', 'counters.company_id')
                ->join('locations', 'locations.id', '=', 'counters.location_id')
                ->get();
    }
}

multi_auth/app/Http/Controllers/Admin/CounterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Counter;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Location;
use Illuminate\Support\Facades\Auth;


class CounterController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        if (is_super_admin()) {
            $counters = Counter::getAll();
        } else {
            $counters = Counter::where('company_id', '=', Auth::user()->company_id)->get();
        }
        return view('admin.counter.list', compact('counters'));
    }

    public function create()
    {
        $companies = Company::select('id', 'companyName')->get();
        if (is_super_admin()) {
            $locations = [];
        } else {
            $locations = Location::select('id', 'locationName')->where('company_id', Auth::user()->company_id)->get();
        }
        return view('admin.counter.create', compact('companies', 'locations'));
    }

    public function store(Request $request, Counter $counter)
    {
        $request->validate([
            'location' => 'required',
            'counterName' => 'required',
            'status' => 'required',
            'address' => 'required',
        ]);

        // return $request->input();
        // exit;
        $counter->company_id = is_super_admin() ? $request->company : Auth::user()->company_id;
        $counter->location_id = decryptIt($request->location);
        $counter->counterName = $request->counterName;
        $counter->address = $request->address;
        $counter->status = $request->status;
        $result = $counter->save();
        if ($result) {
            return redirect()->route('counter.index')->with('success', 'Counter Successfully Added!');
        } else {
            return back()->with('warning', 'Something Wrong, Please Try again');
        }
    }

    public function show(Counter $counter)
    {
        //
    }


    public function edit($id)
    {
        $counter_id = decryptIt($id);

        $counter = Counter::find($counter_id);

        $company_locations = Location::select('id', 'locationName')
            ->where('company_id', '=', $counter->company_id)
            ->get();
        if (is_super_admin()) {
            $locations = [];
        } else {
            $locations = Location::select('id', 'locationName')->where('company_id', Auth::user()->company_id)->get();
        }
        return view('admin.counter.edit', compact('company_locations', 'counter'));
    }

    public function update($id, Request $request, Counter $c )
    {
        $request->validate([
            'location_id' => 'required',
            'counterName' => 'required',
            'status' => 'required',
            'address' => 'required'
        ]);
        $counter_id = decryptIt($id);
        $counter = $c->findOrFail($counter_id);
        return $c;
        // $counter->location_id = decryptIt($request->location);
        // $counter->counterName = $request->counterName;
        // $counter->address = $request->address;
        // $counter->status = $request->status;
        $input = $request->all();
        return $input;

        $result = $counter->save();
        // dd($result);
        if ($result) {
            return redirect()->route('counter.index')->with('success', 'Counter Successfully Updated!');
        } else {
            return back()->with('warning', 'Something Wrong, Please Try again');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Counter  $counter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Counter $counter)
    {
        //
    }
}

multi_auth/resources/views/admin/counter/create.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- stype here -->

@endsection()

@section('main_content')

<h1 class="h3 mb-4 text-gray-800">{{ __('Add new Counter') }}
    <a class="btn btn-primary float-right" href="{{ route('counter.index') }}">Back</a>
</h1>

<div class="card">
    <div class="card-body">
        @if( $msg = Session::get('warning') )
        <div class="alert alert-danger" role="alert">
            {{ $msg }}
        </div>
        @endif

        <form method="POST" action="{{ route('counter.store') }}">
            @csrf
            <div class="form-row">

                @if( is_super_admin() )
                <div class="form-group col-md-6">
                    <label for="company">Company</label>
                    <select name="company" id="company" class="form-control" onchange="getloacationByCompany(this.value)">
                        <option value="">Select one</option>
                        @foreach( $companies as $company)
                        <option value="{{ $company->id }}">{{ $company->companyName }}</option>
                        @endforeach
                    </select>
                </div>
                @endif

                <div class="form-group col-md-6">
                    <label for="location">Location</label>
                    <select name="location" id="location" class="form-control">
                        @foreach ( $locations as $location )
                        <option value="{{$location->id}}">{{ $location->locationName }}</option>
                        @endforeach
                    </select>
                    @error('location')
                    <small id="location" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="counterName">Counter Name</label>
                    <input type="text" value="{{ old('counterName') }}" name="counterName" class="form-control" id="counterName" placeholder="Enter Counter Name">
                    @error('counterName')
                    <small id="counterName" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="status">Status</label>
                    <select name="status" id="status" class="form-control">
                        <option value="">Select one</option>
                        <option value="1">Active</option>
                        <option value="0">Deactive</option>
                    </select>
                    @error('status')
                    <small id="status" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-12">
                    <label for="address">Address</label>
                    <textarea name="address" id="address" cols="30" rows="5" class="form-control"></textarea>
                </div>
                @error('address')
                <small id="address" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>


@endsection()


@section('custom_js')
<!-- seript here -->

<script>

    <?php if( !is_super_admin() ) : ?>
        getloacationByCompany( "{{ Auth::user()->company_id }}")
    <?php endif; ?>


    function getloacationByCompany(id) {
        let company_id = id;

        let location_name = `<option value=''>Select One</option>`;
        let location_value = '';
        if (company_id !== null) {
            $.ajax({
                url: "{{ route('admin.get.company.route.info')}}",
                type: 'POST',
                dataType: 'json',
                data: {
                    _token: '{{ csrf_token() }}',
                    company_id: company_id
                },
                success: function(r) {
                    d = r.routes;
                    console.log(d);
                    if (d) {
                        for (const i in d) {
                            location_name += `<option value='${d[i].id}'>${d[i].locationName}</option>`;
                        }
                    }
                    // document.getElementById("routeName").innerHTML = location_name;
                    document.getElementById('location').innerHTML = location_name;
                }
            });

        }
    }
</script>

@endsection()

multi_auth/resources/views/admin/counter/edit.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- stype here -->

@endsection()

@section('main_content')

<h1 class="h3 mb-4 text-gray-800">{{ __('Update Counter') }}
    <a class="btn btn-primary float-right" href="{{ route('counter.index') }}">Back</a>
</h1>

<div class="card">
    <div class="card-body">
        @if( $msg = Session::get('warning') )
        <div class="alert alert-danger" role="alert">
            {{ $msg }}
        </div>
        @endif
        <form method="POST" action="{{ route('counter.update', $counter->id) }}">
            @csrf
            @method('PATCH')
            <div class="form-row">

                <div class="form-group col-md-6">
                    <label for="location">Location</label>
                    <select name="location_id" id="location" class="form-control">
                        @foreach ( $company_locations as $location )
                        <?php $counter->location_id === $location ? $selected = 'selected' : $selected = '';?>
                        <option {{ $selected }} value="{{$location->id}}">{{ $location->locationName }}</option>
                        @endforeach
                    </select>
                    @error('location')
                    <small id="location" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="counterName">Counter Name</label>
                    <input type="text" value="{{ $counter->counterName }}" name="counterName" class="form-control" id="counterName" placeholder="Enter Driver Name">
                    @error('counterName')
                    <small id="counterName" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="status">Status</label>
                    <select name="status" id="status" class="form-control">
                        <option value="">Select one</option>
                        <option value="1">Active</option>
                        <option value="0">Deactive</option>
                    </select>
                    @error('status')
                    <small id="status" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group col-md-12">
                    <label for="address">Address</label>
                    <textarea name="address" id="address" cols="30" rows="5" class="form-control">{{ $counter->address }}</textarea>
                </div>
                @error('address')
                <small id="address" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>


@endsection()


@section('custom_js')
<!-- seript here -->
<script>

    
</script>

@endsection()

multi_auth/resources/views/admin/counter/list.blade.php
@extends('admin.layouts.app')

@section('style')
<!-- style here -->

@endsection

@section('main_content')
<h1 class="h3 mb-4 text-gray-800">{{ __('Counter List') }}
    <a class="btn btn-primary float-right" href="{{ route('counter.create')}}">Add New</a>
</h1>
@if( $msg = Session::get('success') )
<div class="alert alert-primary" role="alert">
    {{ $msg }}
</div>
@endif
<div class="card">
    <div class="card-body">

        <table class="table table-hover table-sm">
            <thead>
                <tr>
                    <th scope="col">Sl</th>
                    <th scope="col">Counter Name</th>
                    @if( is_super_admin() )
                    <th scope="col">Company Name</th>
                    @endif
                    <th scope="col">Location Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">Status</th>
                    <@if( is_super_admin() )
                    <th scope="col">Is Deleted</th>
                    @endif
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 0; ?>
                @foreach( $counters as $c )
                <?php $i++; ?>
                <tr>
                    <td>{{ $i }}</td>
                    <td>{{ $c->counterName }}</td>
                    @if( is_super_admin() )
                    <td>{{ $c->companyName }}</td>
                    @endif
                    <td>{{ $c->locationName }}</td>
                    <td>{{ $c->address }}</td>
                    <td>{{ status($c->status) }}</td>
                    <td>{{ is_deleted($c->soft_delete) }}</td>
                    <td>
                        <a class="text-primary" href="{{ route('counter.edit', $c->id) }}"><i class="fa fa-edit "></i></a>
                        ||
                        <a class="text-danger" id="delete-driver" data-toggle="modal" data-target="#deleteDriver" url="{{ __('this ') }}"><i class="fa fa-trash "></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>



<!-- temporary delete bus -->
<div class="modal fade" id="deleteDriver" tabindex="-1" role="dialog" aria-labelledby="deleteDriver" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Delete Bus Information?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Delete carefully, You are not retrieve Bus Information.</div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary text-white" id="driver-delete-btn">Delete</a>
            </div>
        </div>
    </div>
</div>
@endsection

@section('custom_js')
<!-- seript here -->

<script>
    $(function() {
        $('#delete-driver').click(function() {
            let id = $(this).attr('url');
            $('#driver-delete-btn').attr({
                href: id
            });
        });
    });
</script>

@endsection